all: propuesta.pdf

propuesta.pdf: propuesta.tex
	pdflatex propuesta.tex
	pdflatex propuesta.tex
	pdflatex propuesta.tex

clean:
	rm -f propuesta.log propuesta.aux

cleanall: clean
	rm -f propuesta.pdf	
